title: Welcome, Traveller.
author: Eddy
email: yineddy@qq.com

description: >
  One way to remember who you are, is to remember who your heroes are. 
  
  --- Steve Jobs


theme: minima

minima:
  skin: solarized-light

show_excerpts: true

header_pages:
  - about.md
